/*
 *   File name: batCfg.h
 *
 *  Created on: 2016年11月15日, 下午7:48:42
 *      Author: victor 
 *   Toolchain: 
 *    Language: C/C++
 * description:

 */

#ifndef __BAT_CFG_H__
#define __BAT_CFG_H__

#include <platform/platform.h>

#define BAT_BLOCK(addr)  ((addr) & PPC_BAT_BLOCK_MASK)

#define IBAT0L_VAL    ( BAT_BLOCK( CONFIG_RAM_BASE_ADDR ) | PPC_LOWER_BAT_PP_READ_ONLY )
#define IBAT0U_VAL    ( BAT_BLOCK( CONFIG_RAM_BASE_ADDR ) | PPC_UPPER_BAT_VALID_SUPERVISOR | PPC_UPPER_BAT_BL_512K )

#define DBAT0L_VAL    ( BAT_BLOCK( CONFIG_RAM_BASE_ADDR ) | PPC_LOWER_BAT_PP_READ_WRITE | PPC_LOWER_BAT_MEMEMORY_COHERENCE | PPC_LOWER_BAT_GUARDED )
#define DBAT0U_VAL    ( BAT_BLOCK( CONFIG_RAM_BASE_ADDR ) | PPC_UPPER_BAT_VALID_SUPERVISOR | PPC_UPPER_BAT_BL_4M )

#define IBAT1L_VAL    ( PPC_LOWER_BAT_PP_NO_ACCESS )
#define IBAT1U_VAL    ( PPC_UPPER_BAT_INVALID )

#define DBAT1L_VAL    PPC_LOWER_BAT_PP_NO_ACCESS
#define DBAT1U_VAL    PPC_UPPER_BAT_INVALID

#define IBAT2L_VAL    ( PPC_LOWER_BAT_PP_NO_ACCESS )
#define IBAT2U_VAL    ( PPC_UPPER_BAT_INVALID )
#define DBAT2L_VAL    ( BAT_BLOCK( CONFIG_ISA_REGS_BASE_ADDR ) | PPC_LOWER_BAT_PP_READ_WRITE | PPC_LOWER_BAT_CACHAE_INHIBITED )
#define DBAT2U_VAL    ( BAT_BLOCK( CONFIG_ISA_REGS_BASE_ADDR ) | PPC_UPPER_BAT_VALID_SUPERVISOR | PPC_UPPER_BAT_VALID_USER | PPC_UPPER_BAT_BL_1M )

#define IBAT3L_VAL    ( PPC_LOWER_BAT_PP_NO_ACCESS )
#define IBAT3U_VAL    ( PPC_UPPER_BAT_INVALID )
#define DBAT3L_VAL    PPC_LOWER_BAT_PP_NO_ACCESS
#define DBAT3U_VAL    PPC_UPPER_BAT_INVALID

#endif

