/*
 *   File name: systemcalls.h
 *
 *  Created on: 2017年3月4日, 下午9:42:06
 *      Author: victor 
 *   Toolchain: 
 *    Language: C/C++
 * description:
 */

#ifndef __INCLUDE_SYSTEMCALLS_H__
#define __INCLUDE_SYSTEMCALLS_H__

enum {
	SYSCALL_PID,
	SYSCALL_PPID,
	SYSCALL_DEBUGCHAR,
	SYSCALL_FORK,
	SYSCALL_EXIT,
	SYSCALL_OPEN,
	SYSCALL_CLOSE,
	SYSCALL_READ,
	SYSCALL_CRTDEV,
	SYSCALL_CHGSIZE,

	SYSCALL_MAPPHYS,
	SYSCALL_WRITE,
	SYSCALL_YIELD,
	SYSCALL_DUPFD,
	SYSCALL_REDIRFD,
	SYSCALL_SETSIGH,
	SYSCALL_ACKSIG,
	SYSCALL_SENDSIG,
	SYSCALL_EXEC,
	SYSCALL_FCNTL,

	SYSCALL_INIT,
	SYSCALL_SLEEP,
	SYSCALL_SEEK,
	SYSCALL_STARTTHREAD,
	SYSCALL_GETTID,
	SYSCALL_SEND,
	SYSCALL_RECEIVE,
	SYSCALL_GETCYCLES,
	SYSCALL_SYNCFS,
	SYSCALL_LINK,

	SYSCALL_UNLINK,
	SYSCALL_MKDIR,
	SYSCALL_RMDIR,
	SYSCALL_MOUNT,
	SYSCALL_UNMOUNT,
	SYSCALL_WAITCHILD,
	SYSCALL_TELL,
	SYSCALL_GETCONF,
	SYSCALL_GETWORK,
	SYSCALL_JOIN,

	SYSCALL_FSTAT,
	SYSCALL_MMAP,
	SYSCALL_MPROTECT,
	SYSCALL_MUNMAP,
	SYSCALL_MATTR,
	SYSCALL_GETUID,
	SYSCALL_SETUID,
	SYSCALL_GETGID,
	SYSCALL_SETGID,
	SYSCALL_CHMOD,

	SYSCALL_CHOWN,
	SYSCALL_GETGROUPS,
	SYSCALL_SETGROUPS,
	SYSCALL_ISINGROUP,
	SYSCALL_ALARM,
	SYSCALL_TSCTOTIME,
	SYSCALL_SEMCRT,
	SYSCALL_SEMOP,
	SYSCALL_SEMDESTROY,
	SYSCALL_SENDRECV,

	SYSCALL_CANCEL,
	SYSCALL_CREATECHAN,
	SYSCALL_DELEGATE,
	SYSCALL_OBTAIN,
	SYSCALL_GETCONFSTR,
	SYSCALL_CLONEMS,
	SYSCALL_JOINMS,
	SYSCALL_MLOCK,
	SYSCALL_MLOCKALL,
	SYSCALL_SEMCRTIRQ,

	SYSCALL_BINDTO,
	SYSCALL_RENAME,
	SYSCALL_GETTOD,
	SYSCALL_UTIME,
	SYSCALL_TRUNCATE,
	SYSCALL_SYMLINK,
	SYSCALL_REQIOPORTS,
	SYSCALL_RELIOPORTS,
	SYSCALL_DEBUG,

	SYSCALL_COUNT,
};

#endif

